// Automatically generated by typings-for-css-modules-loader

export const card: string;
export const decorativeCircle: string;
export const infoRow: string;
export const biographyRow: string;
export const socialRow: string;
export const avatar: string;
