defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.3.0

version: 2
jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run lint

  format:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run format:check

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run: sudo apt install python-pip python-dev
      - run: sudo pip install awscli
      - run: aws s3 sync dist s3://konradschultz-portfolio/ --exclude "*" --include "index.html" --include "bundle.js" --delete

workflows:
  version: 2

  btd:
    jobs:
      - init
      - lint:
          requires:
            - init
      - format:
          requires:
            - init
      - test:
          requires:
            - init
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - init
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - build
