// Automatically generated by typings-for-css-modules-loader

export const header: string;
export const fixed: string;
export const stuck: string;
export const placeholder: string;
export const profileLink: string;
export const profilePicture: string;
